#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-style:
    runs-on: ubuntu-18.04
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@885641592076c27bfb56c028cd5612cdad63e16d
    - uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
      with:
        toolchain: nightly
        default: false
        components: rustfmt
    - name: Check style
      run: cargo +nightly fmt -- --check

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-2019, macos-10.15 ]
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@885641592076c27bfb56c028cd5612cdad63e16d
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose
